version: '3.8'
services:

  # PHP service
  php:
    build:
      context: .
      target: php
      args:
       - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network



  # Database Server
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=location_manager
      - MYSQL_ROOT_PASSWORD=L05yvFmq2bgv0AJh
      - MYSQL_HOST_CACHE_SIZE=0
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 3s  

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    networks:
      - app-network  
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5
      interval: 2s
  
volumes:
  db-data: ~

networks:
  app-network:
    driver: bridge