services:

  # PHP service
  php:
    build:
      context: .
      target: php
      args:
       - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network

  # Database Server
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST_CACHE_SIZE=0
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 3s  
  
volumes:
  db-data: ~

networks:
  app-network:
    driver: bridge